### ISSUE TITLE
Add GitHub links to the `package.json`.

### ISSUE THREAD

**Issue by ChALkeR** [feedhenry/fh-fhc#141]
Atm, npm [fh-fhc](https://www.npmjs.com/package/fh-fhc) page doesn't have any links to this GitHub repo. You should probably add links to the repository and to the issues page.

See https://docs.npmjs.com/files/package.json#bugs, https://docs.npmjs.com/files/package.json#repository.

_The same looks valid for all your other packages, but I'm not going to report those._

**Comment by camilamacedo86** [comment]
@ChALkeR we opened a JIRA for your issue as following.
JIRA: https://issues.jboss.org/browse/FH-3610
Please, feel free to follow it.

**Comment by camilamacedo86** [comment]
It will be done for the next version.
