### ISSUE TITLE
Update Node Version to Align To Supported Jenkins Slaves

### ISSUE THREAD

**Issue by sherl0cks** [feedhenry/fh-fhc#296]
Red Hat is shipping node 4.6.2 on [Jenkins Slaves](https://access.redhat.com/containers/#/repo/57ea8d069c624c035f96f43c). It would be nice to support this version of node.

**Comment by sherl0cks** [comment]
@briangallagher @Keyang FYI

**Comment by Keyang** [comment]
got it. Thanks

~Keyang

**Comment by camilamacedo86** [comment]
I am closing this issue because It was done into : https://issues.jboss.org/browse/FH-3458
