### ISSUE TITLE
Node 6.x Support

### ISSUE THREAD

**Issue by sherl0cks** [feedhenry/fh-fhc#297]
I'm building an Ionic 2 app, which requires node 6.x. This is the message I get when from `fhc -v` with node 6.9.5 installed:

```
fhc ERR! unsupported version 
fhc ERR! unsupported version fhc requires node version: >=0.10 <= 4.4
fhc ERR! unsupported version And you have: v6.9.5
fhc ERR! unsupported version which is not satisfactory.
fhc ERR! unsupported version 
FHC Version: 2.17.1-516
```
I haven't checked to see if functionality actually breaks, but it the error is disconcerting.

**Comment by sherl0cks** [comment]
@briangallagher @Keyang FYI

**Comment by sherl0cks** [comment]
After two weeks of usage, I have no issues. Can we get rid of this warning?

**Comment by aliok** [comment]
Hello @sherl0cks I have filed this issue on our JIRA : https://issues.jboss.org/browse/FH-3458

**Comment by camilamacedo86** [comment]
I am closing this issue because the JIRA : https://issues.jboss.org/browse/FH-3458 is done and merged.
