### ISSUE TITLE
how to remove the rule of sonarqube 

### ISSUE THREAD

**Issue by mc199401** [feedhenry/fh-fhc#362]
i use sonarqube firsttime
so how to remove the rule of sonarqube which named "**Variables should be declared before they are used**" 
if you kown the way to work out it，please help me
thanks

**Comment by camilamacedo86** [comment]
You are using a variable wich was not declared. Following example

`if ( myVar ) {}
`
Where myVar was not declared. To solve it.

```
var myVar;
if ( myVar ) {}

```
