### ISSUE TITLE
Cannot find the options for app type when creating an app

### ISSUE THREAD

**Issue by finp** [feedhenry/fh-fhc#422]
https://github.com/feedhenry/fh-fhc/blob/a26beb04a7f82bdbc7be3d1c8fcf5395495edd70/lib/cmd/fh3/app/create.js#L15

When I tried this, it worked! and showed as a native ios app in studio, so I don't understand the 'type' option:

fhc app create --project=<id> --title='My Native iOS App' --type cloud_nodejs --template=native_ios_swift_blank_app

**Comment by finp** [comment]
type seems to be mandatory, but isn't explained, after creating the json contained "type": "client_native_ios", so is it even used?

**Comment by jasonmadigan** [comment]
see https://github.com/feedhenry/fh-fhc/pull/426

**Comment by mmurphy** [comment]
in addition, when a template is specified the type is contained in the template, e.g. https://github.com/feedhenry/fh-template-apps/blob/54bd0f27b0b7d297605e20666d3c112917b1ace2/global.json#L648

so type should probably not be allowed when template is used

**Comment by camilamacedo86** [comment]
Shows that was solved by the PR: https://github.com/feedhenry/fh-fhc/pull/426. Then I am closing this issue, feel free to check and reopened if it is the case.
