### ISSUE TITLE
Table listing not always working correctly

### ISSUE THREAD

**Issue by ghost** [feedhenry/fh-fhc#5]
When listing apps (fhc apps) using table view (the default view), the data does not always render correctly.

2 issues have been observed:
1. The table borders are lot always aligned correctly
2. The app list ended prematurely - the account I was listing for had 94 apps, but the table list ended after showing only 9 apps. When listed using fhc apps --json, the full list of 94 apps was returned.

Copy of actual output:

    ┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
    ┃ Id                       ┃ Title                                  ┃ Description                                                                                          ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
    ┃ P7aai4P1KUqMWeqCrebC2nHi ┃ 00001                                  ┃ 00001                                                                                                ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
    ┃ 2s6kX_7cjqF8QUSCCMSUkliU ┃ ___App Anatomy                         ┃ This app demonstrates how to use client-side packages to customise application behavior and appeara… ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
    ┃ uG3-dIwPB4-xLinZ3npSD9iV ┃ __Android_Export_Test                  ┃ __Android_Export_Test                                                                        
        ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
    ┃ fhXjl9GZc7oz8ujLomLZADMt ┃ anatomy app clone                      ┃ This app demonstrates how to use client-side packages to customise application behavior and appeara… ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
    ┃ olyP5SFjH6s30Demhk0RTx4E ┃ AnatomyTest                            ┃ This app demonstrates how to use client-side packages to customise application behavior and appeara… ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
    ┃ qECZEwCmNvwZqE_GmUVHuy8u ┃ AndroidViewTest                        ┃ AndroidViewTest                                                                                      ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
    ┃ TLNPydvdRHlU-zKEDXCqAnco ┃ app3                                   ┃ This app demonstrates how to use client-side packages to customise application behavior and appeara… ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
    ┃ H3Mho7Z8se-RecRoqMLnHkEi ┃ App Anatomy                            ┃ This app demonstrates how to use client-side packages to customise application behavior and appeara… ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
    ┃ MtutnAmwLVneYUUda3yeEbK_ ┃ App Anatomy                            ┃ http://docs.feedhenry.com/wiki/App_Anatomy                                                           ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━jfrizelle@DELL-32DXN4J:~$

**Comment by lholmquist** [comment]
This issue is 3 years old,  is it still valid?

**Comment by wei-lee** [comment]
I don't think so. I definitely haven't seen this issue.
